/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as SSubdomainRouteImport } from './routes/s.$subdomain'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminLimitsRouteImport } from './routes/_authenticated/admin.limits'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedBuilderProjectIdRouteImport } from './routes/_authenticated/builder.$projectId'
import { Route as ApiPublicAurapayWebhookRouteImport } from './routes/api/public/aurapay-webhook'
import { Route as ApiPublicGenerateRouteImport } from './routes/api/public/generate'
import { Route as ApiPublicSiteRouteImport } from './routes/api/public/site'
import { Route as AuthenticatedAdminPlansIndexRouteImport } from './routes/_authenticated/admin.plans.index'
import { Route as AuthenticatedAdminPlansIdRouteImport } from './routes/_authenticated/admin.plans.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SSubdomainRoute = SSubdomainRouteImport.update({
  id: '/s/$subdomain',
  path: '/s/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLimitsRoute =
  AuthenticatedAdminLimitsRouteImport.update({
    id: '/limits',
    path: '/limits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedBuilderProjectIdRoute =
  AuthenticatedBuilderProjectIdRouteImport.update({
    id: '/builder/$projectId',
    path: '/builder/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAurapayWebhookRoute = ApiPublicAurapayWebhookRouteImport.update({
  id: '/api/public/aurapay-webhook',
  path: '/api/public/aurapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateRoute = ApiPublicGenerateRouteImport.update({
  id: '/api/public/generate',
  path: '/api/public/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteRoute = ApiPublicSiteRouteImport.update({
  id: '/api/public/site',
  path: '/api/public/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPlansIndexRoute =
  AuthenticatedAdminPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansIdRoute =
  AuthenticatedAdminPlansIdRouteImport.update({
    id: '/plans/$id',
    path: '/plans/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/limits': typeof AuthenticatedAdminLimitsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/builder/$projectId': typeof AuthenticatedBuilderProjectIdRoute
  '/api/public/aurapay-webhook': typeof ApiPublicAurapayWebhookRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/site': typeof ApiPublicSiteRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/plans/$id': typeof AuthenticatedAdminPlansIdRoute
  '/admin/plans/': typeof AuthenticatedAdminPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/limits': typeof AuthenticatedAdminLimitsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/builder/$projectId': typeof AuthenticatedBuilderProjectIdRoute
  '/api/public/aurapay-webhook': typeof ApiPublicAurapayWebhookRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/site': typeof ApiPublicSiteRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/plans/$id': typeof AuthenticatedAdminPlansIdRoute
  '/admin/plans': typeof AuthenticatedAdminPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/limits': typeof AuthenticatedAdminLimitsRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/builder/$projectId': typeof AuthenticatedBuilderProjectIdRoute
  '/api/public/aurapay-webhook': typeof ApiPublicAurapayWebhookRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/site': typeof ApiPublicSiteRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/plans/$id': typeof AuthenticatedAdminPlansIdRoute
  '/_authenticated/admin/plans/': typeof AuthenticatedAdminPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/payment/success'
    | '/s/$subdomain'
    | '/admin/analytics'
    | '/admin/limits'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/settings'
    | '/admin/users'
    | '/builder/$projectId'
    | '/api/public/aurapay-webhook'
    | '/api/public/generate'
    | '/api/public/site'
    | '/admin/'
    | '/admin/plans/$id'
    | '/admin/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard'
    | '/payment/success'
    | '/s/$subdomain'
    | '/admin/analytics'
    | '/admin/limits'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/settings'
    | '/admin/users'
    | '/builder/$projectId'
    | '/api/public/aurapay-webhook'
    | '/api/public/generate'
    | '/api/public/site'
    | '/admin'
    | '/admin/plans/$id'
    | '/admin/plans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/payment/success'
    | '/s/$subdomain'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/limits'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/builder/$projectId'
    | '/api/public/aurapay-webhook'
    | '/api/public/generate'
    | '/api/public/site'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/plans/$id'
    | '/_authenticated/admin/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  SSubdomainRoute: typeof SSubdomainRoute
  ApiPublicAurapayWebhookRoute: typeof ApiPublicAurapayWebhookRoute
  ApiPublicGenerateRoute: typeof ApiPublicGenerateRoute
  ApiPublicSiteRoute: typeof ApiPublicSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$subdomain': {
      id: '/s/$subdomain'
      path: '/s/$subdomain'
      fullPath: '/s/$subdomain'
      preLoaderRoute: typeof SSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/limits': {
      id: '/_authenticated/admin/limits'
      path: '/limits'
      fullPath: '/admin/limits'
      preLoaderRoute: typeof AuthenticatedAdminLimitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/builder/$projectId': {
      id: '/_authenticated/builder/$projectId'
      path: '/builder/$projectId'
      fullPath: '/builder/$projectId'
      preLoaderRoute: typeof AuthenticatedBuilderProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/aurapay-webhook': {
      id: '/api/public/aurapay-webhook'
      path: '/api/public/aurapay-webhook'
      fullPath: '/api/public/aurapay-webhook'
      preLoaderRoute: typeof ApiPublicAurapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate': {
      id: '/api/public/generate'
      path: '/api/public/generate'
      fullPath: '/api/public/generate'
      preLoaderRoute: typeof ApiPublicGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site': {
      id: '/api/public/site'
      path: '/api/public/site'
      fullPath: '/api/public/site'
      preLoaderRoute: typeof ApiPublicSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/plans/': {
      id: '/_authenticated/admin/plans/'
      path: '/plans'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof AuthenticatedAdminPlansIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans/$id': {
      id: '/_authenticated/admin/plans/$id'
      path: '/plans/$id'
      fullPath: '/admin/plans/$id'
      preLoaderRoute: typeof AuthenticatedAdminPlansIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminLimitsRoute: typeof AuthenticatedAdminLimitsRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPlansIdRoute: typeof AuthenticatedAdminPlansIdRoute
  AuthenticatedAdminPlansIndexRoute: typeof AuthenticatedAdminPlansIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminLimitsRoute: AuthenticatedAdminLimitsRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPlansIdRoute: AuthenticatedAdminPlansIdRoute,
  AuthenticatedAdminPlansIndexRoute: AuthenticatedAdminPlansIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedBuilderProjectIdRoute: typeof AuthenticatedBuilderProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedBuilderProjectIdRoute: AuthenticatedBuilderProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  SSubdomainRoute: SSubdomainRoute,
  ApiPublicAurapayWebhookRoute: ApiPublicAurapayWebhookRoute,
  ApiPublicGenerateRoute: ApiPublicGenerateRoute,
  ApiPublicSiteRoute: ApiPublicSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
